swagger: '2.0'
host: ece461-p2-t3.appspot.com
info:
  contact:
    email: davisjam@purdue.edu
    name: Prof. Davis
    url: 'http://davisjam.github.io'
  description: 'API for ECE 461/Fall 2021/Project 2: A Trustworthy Module Registry'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'http://swagger.io/terms/'
  title: ECE 461 - Fall 2021 - Project 2
  version: 1.0.0
paths:
  /authenticate:
    description: >-
      If your system supports the authentication scheme described in the spec,
      then:


      1. The obtained token should be provided to the other endpoints via the
      "X-Authorization" header.

      2. The "Authorization" header is *required* in your system.


      Otherwise, this endpoint should return HTTP 501 "Not implemented", and the
      "X-Authorization" header should be unused for the other endpoints.
    put:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/AuthenticationRequest'
      responses:
        '200':
          description: Success.
          schema:
            $ref: '#/definitions/AuthenticationToken'
        '401':
          description: Authentication failed (e.g. no such user or invalid password)
        '501':
          description: This system does not support authentication.
      operationId: CreateAuthToken
    summary: Authenticate this user -- get an access token.
  /package:
    parameters:
      - description: >-
          The spec permits you to use any token format you like. You could, for
          example, look into JSON Web Tokens ("JWT", pronounced "jots"):
          https://jwt.io.
        in: header
        name: X-Authorization
        required: true
        type: string
    description: >-
      The "ID" field in the request body allows the user to use their own ID
      scheme. If this ID is already in use, the system chooses a new ID and
      indicates this in the response body.
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Package'
      responses:
        '201':
          description: Success. Check the ID in the returned metadata for the official ID.
          schema:
            $ref: '#/definitions/PackageMetadata'
        '400':
          description: Malformed request.
        '403':
          description: Package exists already.
      operationId: PackageCreate
    summary: Create a version of a package
  '/package/byName/{name}':
    parameters:
      - description: |-
          Name of a package.

          - Names should only use typical "keyboard" characters.
          - The name "*" is reserved. See the `/packages` API for its meaning.
        in: path
        name: name
        required: true
        type: string
      - description: >-
          The spec permits you to use any token format you like. You could, for
          example, look into JSON Web Tokens ("JWT", pronounced "jots"):
          https://jwt.io.
        in: header
        name: X-Authorization
        type: string
    delete:
      parameters:
        - description: |-
            Name of a package.

            - Names should only use typical "keyboard" characters.
            - The name "*" is reserved. See the `/packages` API for its meaning.
          in: path
          name: name
          required: true
          type: string
      responses:
        '200':
          description: Package is deleted.
        '400':
          description: No such package.
      operationId: PackageByNameDelete
      summary: Delete all versions of this package.
    get:
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Package history
          schema:
            items:
              $ref: '#/definitions/PackageHistoryEntry'
            type: array
        '400':
          description: No such package.
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
      description: Return the history of this package (all versions).
      operationId: PackageByNameGet
    summary: Interact with the package with this name
  '/package/{id}':
    parameters:
      - description: Package ID
        in: path
        name: id
        required: true
        type: string
      - description: >-
          The spec permits you to use any token format you like. You could, for
          example, look into JSON Web Tokens ("JWT", pronounced "jots"):
          https://jwt.io.
        in: header
        name: X-Authorization
        type: string
    delete:
      parameters:
        - description: Package ID
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: Package is deleted.
        '400':
          description: No such package.
      operationId: PackageDelete
      summary: Delete this version of the package.
    get:
      produces:
        - application/json
      parameters:
        - description: ID of package to fetch
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: pet response
          schema:
            $ref: '#/definitions/Package'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
      description: Return this package.
      operationId: PackageRetrieve
    put:
      consumes:
        - application/json
      parameters:
        - description: ''
          in: path
          name: id
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Package'
      responses:
        '200':
          description: Success.
        '400':
          description: Malformed request (e.g. no such package).
      description: >-
        The name, version, and ID must match.


        The package contents (from PackageData) will replace the previous
        contents.
      operationId: PackageUpdate
      summary: Update this version of the package.
    summary: Interact with the package with this ID
  '/package/{id}/rate':
    parameters:
      - in: path
        name: id
        required: true
        type: string
      - description: >-
          The spec permits you to use any token format you like. You could, for
          example, look into JSON Web Tokens ("JWT", pronounced "jots"):
          https://jwt.io.
        in: header
        name: X-Authorization
        type: string
    get:
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Rating. Only use this if each metric was computed successfully.
          schema:
            $ref: '#/definitions/PackageRating'
        '400':
          description: No such package.
        '500':
          description: The package rating system choked on at least one of the metrics.
      operationId: PackageRate
    summary: Get the rating for this package.
  /packages:
    parameters:
      - description: >-
          The spec permits you to use any token format you like. You could, for
          example, look into JSON Web Tokens ("JWT", pronounced "jots"):
          https://jwt.io.
        in: header
        name: X-Authorization
        type: string
    description: >-
      Search for packages satisfying the indicated query.


      If you want to enumerate all packages, provide an array with a single
      PackageQuery whose name is "*".


      The response is paginated; the response header includes the offset to use
      in the next query.
    get:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: >-
            Provide this for pagination. If not provided, returns the first page
            of results.
          in: query
          name: offset
          required: false
          type: string
        - in: body
          name: body
          required: true
          schema:
            items:
              $ref: '#/definitions/PackageQuery'
            type: array
      responses:
        '200':
          description: List of packages
          headers:
            offset: {}
          schema:
            items:
              $ref: '#/definitions/PackageMetadata'
            type: array
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
      description: Get any packages fitting the query.
      operationId: PackagesList
      summary: Get packages
    summary: Query the registry.
  /reset:
    parameters:
      - description: >-
          The spec permits you to use any token format you like. You could, for
          example, look into JSON Web Tokens ("JWT", pronounced "jots"):
          https://jwt.io.
        in: header
        name: X-Authorization
        type: string
    delete:
      parameters: []
      responses:
        '200':
          description: Registry is reset.
        '401':
          description: You do not have permission to reset the registry.
      operationId: RegistryReset
    summary: Reset registry
definitions:
  AuthenticationRequest:
    description: ''
    properties:
      Secret:
        $ref: '#/definitions/UserAuthenticationInfo'
        description: ''
      User:
        $ref: '#/definitions/User'
        description: ''
    required:
      - User
      - Secret
    type: object
  AuthenticationToken:
    description: >-
      The spec permits you to use any token format you like. You could, for
      example, look into JSON Web Tokens ("JWT", pronounced "jots"):
      https://jwt.io.
    type: string
  EnumerateOffset:
    description: Offset in pagination.
    example: '1'
    type: string
  Error:
    properties:
      code:
        format: int32
        type: integer
      message:
        type: string
    required:
      - code
      - message
  Package:
    properties:
      data:
        $ref: '#/definitions/PackageData'
        description: ''
      metadata:
        $ref: '#/definitions/PackageMetadata'
        description: ''
    required:
      - metadata
      - data
    type: object
  PackageData:
    description: |-
      This is a "union" type.
      - On package upload, either Content or URL should be set.
      - On package update, exactly one field should be set.
      - On download, the Content field should be set.
    properties:
      Content:
        description: >-
          Package contents. This is the zip file uploaded by the user. (Encoded
          as text using a Base64 encoding).


          This will be a zipped version of an npm package's GitHub repository,
          minus the ".git/" directory." It will, for example, include the
          "package.json" file that can be used to retrieve the project homepage.


          See
          https://docs.npmjs.com/cli/v7/configuring-npm/package-json#homepage.
        type: string
      JSProgram:
        description: A JavaScript program (for use with sensitive modules).
        type: string
      URL:
        description: Package URL (for use in public ingest).
        type: string
    type: object
  PackageHistoryEntry:
    description: One entry of the history of this package.
    properties:
      Action:
        description: ''
        enum:
          - CREATE
          - UPDATE
          - DOWNLOAD
          - RATE
        type: string
      Date:
        description: Date of activity.
        format: date-time
        type: string
      PackageMetadata:
        $ref: '#/definitions/PackageMetadata'
        description: ''
      User:
        $ref: '#/definitions/User'
        description: ''
    required:
      - User
      - Date
      - PackageMetadata
      - Action
    type: object
  PackageID:
    description: ''
    type: string
  PackageMetadata:
    description: >-
      The "Name" and "Version" are used as a unique identifier pair when
      uploading a package.


      The "ID" is used as an internal identifier for interacting with existing
      packages.
    properties:
      ID:
        $ref: '#/definitions/PackageID'
        description: 'Unique ID for use with the /package/{id} endpoint.'
        example: '123567192081501'
      Name:
        $ref: '#/definitions/PackageName'
        description: Package name
        example: my-package
      Version:
        description: Package version
        example: 1.2.3
        type: string
    required:
      - Name
      - Version
      - ID
    type: object
  PackageName:
    description: |-
      Name of a package.

      - Names should only use typical "keyboard" characters.
      - The name "*" is reserved. See the `/packages` API for its meaning.
    type: string
  PackageQuery:
    description: ''
    properties:
      Name:
        $ref: '#/definitions/PackageName'
        description: ''
      Version:
        $ref: '#/definitions/SemverRange'
        description: ''
    required:
      - Name
    type: object
  PackageRating:
    description: >-
      Package rating (cf. Project 1).


      If the Project 1 that you inherited does not support one or more of the
      original properties, denote this with the value "-1".
    properties:
      BusFactor:
        description: ''
        format: double
        type: number
      Correctness:
        description: ''
        format: double
        type: number
      GoodPinningPractice:
        description: >-
          The fraction of its dependencies that are pinned to at least a
          specific major+minor version, e.g. version 2.3.X of a package. (If
          there are zero dependencies, they should receive a 1.0 rating. If
          there are two dependencies, one pinned to this degree, then they
          should receive a ½ = 0.5 rating).
        format: double
        type: number
      LicenseScore:
        description: ''
        format: double
        type: number
      RampUp:
        description: ''
        format: double
        type: number
      ResponsiveMaintainer:
        description: ''
        format: double
        type: number
    required:
      - RampUp
      - Correctness
      - BusFactor
      - ResponsiveMaintainer
      - LicenseScore
      - GoodPinningPractice
    type: object
  SemverRange:
    description: ''
    example: |-
      Exact (1.2.3)
      Bounded range (1.2.3-2.1.0)
      Carat (^1.2.3)
      Tilde (~1.2.0)
    type: string
  User:
    description: ''
    properties:
      isAdmin:
        description: Is this user an admin?
        type: boolean
      name:
        description: ''
        example: Alfalfa
        type: string
    required:
      - name
      - isAdmin
    type: object
  UserAuthenticationInfo:
    description: Authentication info for a user
    properties:
      password:
        description: 'Password for a user. Per the spec, this should be a "strong" password.'
        type: string
    required:
      - password
    type: object
securityDefinitions:
  UserAndPasswordYieldsToken:
    description: Use the /authentication endpoint to obtain an authorization token.
    in: header
    name: X-Authorization
    type: apiKey
x-components: {}

