on: push

jobs:
  setup-deploy:
    name: Setup
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: deploy
        id: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          version: v1
          working_directory: $GITHUB_WORKSPACE/package_moduleshelf