on: push

jobs:
  setup-deploy:
    name: Setup
    runs-on: ubuntu-latest
    environment: production

    steps:
      - id: Deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        version: v1
        deliverables: package_moduleshelf/app.yaml
      
      # Example of using the output
      - id: test
      run: curl "${{ steps.deploy.outputs.url }}"